apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ndcapstoneinfra-cluster
  region: us-west-2

managedNodeGroups:
  - name: ng-eks-public-new
    instanceType: t2.small
    minSize: 2
    maxSize: 4
