apiVersion: v1
kind: Service
metadata: 
  name: udacitycapstoneproject-service
spec:
  selector:
    app: udacitycapstoneproject
  type: LoadBalancer
  ports:
    - nodePort: 30087
      port: 80
      targetPort: 80
