version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9.9

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      # run lint!
      - run:
          name: run lint
          command: |
            . venv/bin/activate
            make lint

  build_push_image:
    machine: true
    steps:
      - checkout

      # build the application image
      - run: docker build --tag=udacitycapstoneproject .
      
      # start proprietary DB using private Docker image
      # with credentials stored in the UI
      - run: 
          name: Authenticate, tag & push docker image
          command: |
            # Create dockerpath
            dockerpath="061770600068.dkr.ecr.us-west-2.amazonaws.com/udacitycapstoneproject:latest"

            # Authenticate & tag
            aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 061770600068.dkr.ecr.us-west-2.amazonaws.com
            echo "Docker ID and Image: $dockerpath"
            docker tag udacitycapstoneproject:latest $dockerpath

            # Push image to a docker repository
            docker push $dockerpath
  

workflows:
  workflow:
    jobs:
      - build
      - build_push_image:
          requires: [build]